#!/bin/bash
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
sudo apt-get -y update
sudo apt-get -y install awscli ruby2.0 build-essential libssl-dev libffi-dev python-dev git libmysqlclient-dev monit python-pip nginx jq
cd /home/ubuntu
aws s3 cp s3://aws-codedeploy-us-west-2/latest/install . --region us-west-2
chmod +x ./install
sudo ./install auto

export AWS_DEFAULT_REGION='us-west-2'

get_instance_tags () {
    instance_id=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
    echo $(aws ec2 describe-tags --filters "Name=resource-id,Values=$instance_id")
}

tags_to_env () {
    tags=$1

    for key in $(echo $tags | jq -r ".[][].Key"); do
        value=$(echo $tags | jq -r ".[][] | select(.Key==\"$key\") | .Value")
        key=$(echo $key | tr '-' '_' | /usr/bin/tr '[:lower:]' '[:upper:]')
        echo "export $key='$value'" >> ~/.profile
    done
}

instance_tags=$(get_instance_tags)

tags_to_env "$instance_tags"
